name: flutter_map_marker_popup_example
description: Example for Flutter Map Marker Popups.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  latlong2: ^0.8.0
  flutter_map:
    git:
      url: https://github.com/manle93/flutter_map.git
      ref: master
  flutter_map_marker_popup:
    path: ../

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
